Let Firewall app call setUidsAllowedOnRestrictedNetworks
* Datura is now running as it's own uid to call setFirewallUidRule
* It fails otherwise:
java.lang.SecurityException: Only system can set this setting.
   at android.net.ConnectivitySettingsManager.setUidsAllowedOnRestrictedNetworks(ConnectivitySettingsManager.java:1080)
   at org.calyxos.datura.settings.SettingsManager.setAppRestrictAll(SettingsManager.java:89)
* This should be safe since we're only modifying this one function,
  and the datura uid would only be available to 'platform' apps,
  so any third party apps would not be able to get it.

Change-Id: I55f6feb61ac17dcb6d4afb12788f042bc71b6e1b