Include LineageSettings for tests
TODO: Still need to resolve this (mocking or something?):
```
[1/1] com.android.server.ConnectivityServiceTest#testLegacyLockdownVpn: FAILED (1.192s)

STACKTRACE:
java.lang.NullPointerException: Attempt to invoke interface method 'android.os.Bundle android.content.IContentProvider.call(android.content.AttributionSource, java.lang.String, java.lang.String, java.lang.String, android.os.Bundle)' on a null object reference
        at lineageos.providers.LineageSettings$NameValueCache.getStringForUser(LineageSettings.java:296)
        at lineageos.providers.LineageSettings$Global.getStringForUser(LineageSettings.java:3107)
        at lineageos.providers.LineageSettings$Global.getString(LineageSettings.java:3089)
        at com.android.server.connectivity.Vpn.isGlobalVpn(Vpn.java:700)
        at com.android.server.connectivity.Vpn.createUserAndRestrictedProfilesRanges(Vpn.java:1745)
```

Issue: calyxos#1448
Change-Id: Ia0a1d179034552992c6b33c157d2f77957635651